name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
    PYTHON_VERSION: '3.12'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install MinGW
        run: choco install mingw --yes --force

      - name: Add MinGW to PATH
        shell: powershell
        run: |
          $mingwPath = "C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
          echo "##[add-path]$mingwPath"

      - name: Compile PyInstaller bootloader
        run: |
          cd PyInstaller/bootloader
          python waf distclean
          python waf configure --gcc
          python waf all --target-arch=64bit

      - name: Install PyInstaller (with compiled bootloader)
        run: |
          cd PyInstaller
          pip install .

      - name: Install app dependencies
        run: |
          pip install -r requirements.txt

      - name: Build executable
        run: |
          pyinstaller --onefile --noconsole --icon=icon.ico --name=NoMoreBorder main.py

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          artifacts: dist/NoMoreBorder.exe
          name: ${{ github.ref_name }}
          generateReleaseNotes: true
          body: |
            Made with PyInstaller. Python ${{ env.PYTHON_VERSION }} and custom-compiled bootloader (MinGW).

            **NOTE**
            Run it as it is. If having issues run as administrator.
            You can use this one or compile your own. Details on how to do that are given in the [README](https://github.com/invcble/NoMoreBorder?tab=readme-ov-file#or-option-2-run-as-a-script--compile-your-own-exe).
